export const BITD = {
  attributeLinks: {
    insight: ["hunt", "study", "survey", "tinker"],
    prowess: ["finesse", "prowl", "skirmish", "wreck"],
    resolve: ["attune", "command", "consort", "sway"],
  },
  linkedForeign: {
    scoundrel: ["contacts", "goals"],
    crew: ["members", "contacts", "relatedFactions", "goals"],
    faction: ["members", "relatedFactions", "goals"],
    crewType: ["abilities", "cohorts", "claimsMap", "upgrades", "contacts"],
  },
  supportedLinks: {
    scoundrel: {
      npc: "contacts",
      clock: "goals",
    },
    crew: {
      scoundrel: "members",
      npc: "contacts",
      faction: "relatedFactions",
      clock: "goals",
    },
    faction: {
      faction: "relatedFactions",
      npc: "members",
      clock: "goals",
    },
    playbook: {
      abilityScoundrel: "abilities",
      tool: "inventory",
    },
    crewType: {
      abilityCrew: "abilities",
      claim: "claimsMap",
      cohort: "cohorts",
      upgrade: "upgrades",
    },
  },
  forLoad: {
    scoundrel: {
      container: "playbook",
      types: ["abilities", "inventory"],
    },
    crew: {
      container: "crewType",
      types: ["abilities", "cohorts", "upgrades"],
    },
  },
  defaultItems: {
    scoundrel: [
      "HZxYeBCQ4bZ632WU",
      "2H0lH4IeGq22kDyg",
      "cF0hFmTlXxI8CKSC",
      "0k2HLJEIIc2MT7cH",
      "FFNGcKvAeOjoGyI8",
      "jWTVSlCXWeOiGbfg",
      "vgMbINvoCQJAYp4q",
      "6NrhTvPbJTJJUn4s",
      "vrPi03rFguHYueWZ",
      "gnv9k4enWnR13mW4",
      "SapwXYuraydiNjej",
      "P95oe4AZgSomPqPs",
      "brU5pWiXWlG5o1Mi",
      "oZOplJcmR6CjQZbO",
      "Wxoq19qr9LEuuNp4",
      "IDUBdq7KVd3dxC5W",
    ],
    crew: [
      "QYT0VHUnH7NvELXE",
      "0jzSjAD7aC7sTJWB",
      "JRUITBP7ejrAS7DE",
      "a78hFI8IrZ4GvmMO",
      "gwPjJVlyOdpHHkSZ",
      "iK5vthVkcbBjwl9W",
      "eOYEeQFnf0Lpflst",
      "sIzU9C2J8Ff888hZ",
      "LGG0DCb9qv2Pijy7",
      "BJG1pPeOQQHc4Sxb",
      "DYvuI3w5fSwLstvG",
      "LOPmlnXrAI5baXOx",
    ],
    prison: [
      "DyZp6G4WpZ5Kfq0C",
      "rOKYroipfUkG3KWV",
      "wzF9qDYgEhPwK4EP",
      "gZZkjnypiaQXVqCv",
      "axBT7dgd8ILdxTuR",
      "",
      "axBT7dgd8ILdxTuR",
      "wzF9qDYgEhPwK4EP",
      "pZ8NipIv4FzvesCm",
      "rOKYroipfUkG3KWV",
      "wzF9qDYgEhPwK4EP",
      "wzF9qDYgEhPwK4EP",
    ],
  },
  defaultTraumas: [
    "BITD.Scoundrel.Traumas.Cold",
    "BITD.Scoundrel.Traumas.Haunted",
    "BITD.Scoundrel.Traumas.Obsessed",
    "BITD.Scoundrel.Traumas.Paranoid",
    "BITD.Scoundrel.Traumas.Reckless",
    "BITD.Scoundrel.Traumas.Soft",
    "BITD.Scoundrel.Traumas.Unstable",
    "BITD.Scoundrel.Traumas.Vicious",
  ],
  load: {
    light: "BITD.Scoundrel.Load.Light",
    normal: "BITD.Scoundrel.Load.Normal",
    heavy: "BITD.Scoundrel.Load.Heavy",
    encumbered: "BITD.Scoundrel.Load.Encumbered",
  },
  holdTypes: { strong: "BITD.Crew.Hold.Strong", weak: "BITD.Crew.Hold.Weak" },
  factionTypes: {
    underworld: "BITD.Faction.Types.Underworld",
    fringe: "BITD.Faction.Types.Fringe",
    institution: "BITD.Faction.Types.Institution",
    laborTrade: "BITD.Faction.Types.LaborTrade",
    other: "BITD.Faction.Types.Other"
  },
  statusTypes: {
    allies: "BITD.Faction.Status.Allies",
    friendly: "BITD.Faction.Status.Friendly",
    helpful: "BITD.Faction.Status.Helpful",
    neutral: "BITD.Faction.Status.Neutral",
    interfering: "BITD.Faction.Status.Interfering",
    hostile: "BITD.Faction.Status.Hostile",
    war: "BITD.Faction.Status.War",
  },
  cohort: {
    types: {
      gang: "BITD.Cohort.Type.Gang",
      expert: "BITD.Cohort.Type.Expert",
    },
    harm: {
      0: "BITD.Cohort.Harms.NoHarm",
      1: "BITD.Cohort.Harms.Weakened",
      2: "BITD.Cohort.Harms.Impaired",
      3: "BITD.Cohort.Harms.Broken",
      4: "BITD.Cohort.Harms.Dead",
    },
  },
  toolType: {
    common: "BITD.Tool.Common",
    special: "BITD.Tool.Special",
  },
  upgradeType: {
    common: "BITD.Upgrade.Common",
    special: "BITD.Upgrade.Special",
  },

  relationshipClasses: ["rival", "neutral", "friend", "special"],

  rolls: {
    type: {
      action: "BITD.Roll.Type.Action",
      resistance: "BITD.Roll.Type.Resistance",
      fortune: "BITD.Roll.Type.Fortune",
      information: "BITD.Roll.Type.GatherInformation",
      engagement: "BITD.Roll.Type.Engagement",
      asset: "BITD.Roll.Type.AcquireAsset",
      vice: "BITD.Roll.Type.IndulgeVice",
    },
    rollAs: {
      action: "BITD.Roll.Type.Action",
      fortune: "BITD.Roll.Type.Fortune",
    },
    attributes: {
      insight: "BITD.Attributes.Insight",
      prowess: "BITD.Attributes.Prowess",
      resolve: "BITD.Attributes.Resolve",
    },
    actions: {
      hunt: "BITD.Actions.Hunt",
      study: "BITD.Actions.Study",
      survey: "BITD.Actions.Survey",
      tinker: "BITD.Actions.Tinker",
      finesse: "BITD.Actions.Finesse",
      prowl: "BITD.Actions.Prowl",
      skirmish: "BITD.Actions.Skirmish",
      wreck: "BITD.Actions.Wreck",
      attune: "BITD.Actions.Attune",
      command: "BITD.Actions.Command",
      consort: "BITD.Actions.Consort",
      sway: "BITD.Actions.Sway",
    },
    position: {
      controlled: "BITD.Roll.Position.Controlled",
      risky: "BITD.Roll.Position.Risky",
      desperate: "BITD.Roll.Position.Desperate",
    },
    effect: {
      zero: "BITD.Roll.Effect.Zero",
      limited: "BITD.Roll.Effect.Limited",
      standard: "BITD.Roll.Effect.Standard",
      great: "BITD.Roll.Effect.Great",
      extreme: "BITD.Roll.Effect.Extreme",
    },
    fortuneRollResult: {
      fail: "Zero",
      mixed: "Limited",
      success: "Standard",
      critical: "Great",
    },
    effectSequence: ["zero", "limited", "standard", "great", "extreme"],
  },

  clockTypes: {
    4: 4,
    6: 6,
    8: 8,
    10: 10,
    12: 12,
  },

  claims: {
    empty: {
      actor: {
        id: "",
        name: "",
        type: "turf",
        active: false,
        effect: "",
      },
      item: {
        id: "",
        uuid: "",
        name: "",
        type: "turf",
        active: false,
      },
    },
  },
  settingsSupported: ["scoundrel", "crew"]
};
