name: Prepare Release

on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'main'
    paths:
      - 'package.json'

jobs:
  prepare:
    if: ${{ github.event.pull_request.head.repo.full_name == 'GMonlineua/blades-in-the-dark-fvtt' && github.event.pull_request.head.ref == 'development' }}
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: development

      - name: Get Version
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Update system.json
        run: |
          DOWNLOAD_URL="https://github.com/GMonlineua/blades-in-the-dark-fvtt/releases/download/v${{ env.VERSION }}/foundry.zip"
          jq --arg v "${{ env.VERSION }}" --arg d "$DOWNLOAD_URL" '.version = $v | .download = $d' system.json > tmp.json && mv tmp.json system.json

      - name: Update Readme
        run: |
          LINK="https://img.shields.io/badge/Version-${{ env.VERSION }}-informational?style=flat-square"
          sed -i "s|\[Version\]:.*|\[Version\]: $LINK|" README.md

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Compile CSS from SCSS
        run: npm run build:css

      - name: Commit AutoBuild
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md css/* system.json
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Auto update files"
            git push origin development
          fi
